
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;

	private global::Gtk.HBox hbox1;

	private global::Gtk.ComboBox cbox;

	private global::Gtk.Button refresh;

	private global::Gtk.Button url;

	private global::Gtk.HBox hbox2;

	private global::Gtk.Button play;

	private global::Gtk.Button pause;

	private global::Gtk.Button stop;

	private global::Gtk.HScale scale;

	private global::Gtk.VBox vbox2;

	private global::Gtk.Label txt;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("VLCia");
		this.Icon = global::Stetic.IconLoader.LoadIcon(this, "gtk-media-play", global::Gtk.IconSize.Menu);
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.cbox = global::Gtk.ComboBox.NewText();
		this.cbox.Sensitive = false;
		this.cbox.Name = "cbox";
		this.hbox1.Add(this.cbox);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.cbox]));
		w1.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.refresh = new global::Gtk.Button();
		this.refresh.CanFocus = true;
		this.refresh.Name = "refresh";
		this.refresh.UseUnderline = true;
		this.refresh.Label = global::Mono.Unix.Catalog.GetString("Refresh");
		this.hbox1.Add(this.refresh);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.refresh]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.url = new global::Gtk.Button();
		global::Gtk.Tooltips w3 = new Gtk.Tooltips();
		w3.SetTip(this.url, "Copies to clipboard", "Copies to clipboard");
		this.url.CanFocus = true;
		this.url.Name = "url";
		this.url.UseUnderline = true;
		this.url.Label = global::Mono.Unix.Catalog.GetString("URL");
		this.hbox1.Add(this.url);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.url]));
		w4.Position = 2;
		w4.Expand = false;
		w4.Fill = false;
		this.vbox1.Add(this.hbox1);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.play = new global::Gtk.Button();
		this.play.CanFocus = true;
		this.play.Name = "play";
		this.play.UseUnderline = true;
		this.play.Label = global::Mono.Unix.Catalog.GetString("Play");
		this.hbox2.Add(this.play);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.play]));
		w6.Position = 0;
		// Container child hbox2.Gtk.Box+BoxChild
		this.pause = new global::Gtk.Button();
		this.pause.CanFocus = true;
		this.pause.Name = "pause";
		this.pause.UseUnderline = true;
		this.pause.Label = global::Mono.Unix.Catalog.GetString("Pause");
		this.hbox2.Add(this.pause);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.pause]));
		w7.Position = 1;
		// Container child hbox2.Gtk.Box+BoxChild
		this.stop = new global::Gtk.Button();
		this.stop.CanFocus = true;
		this.stop.Name = "stop";
		this.stop.UseUnderline = true;
		this.stop.Label = global::Mono.Unix.Catalog.GetString("Stop");
		this.hbox2.Add(this.stop);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.stop]));
		w8.Position = 2;
		this.vbox1.Add(this.hbox2);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
		w9.Position = 1;
		w9.Expand = false;
		w9.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.scale = new global::Gtk.HScale(null);
		this.scale.HeightRequest = 55;
		this.scale.Sensitive = false;
		this.scale.CanFocus = true;
		this.scale.Name = "scale";
		this.scale.Adjustment.Upper = 0.01D;
		this.scale.Adjustment.PageIncrement = 5D;
		this.scale.Adjustment.StepIncrement = 0.5D;
		this.scale.DrawValue = true;
		this.scale.Digits = 0;
		this.scale.ValuePos = ((global::Gtk.PositionType)(2));
		this.vbox1.Add(this.scale);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.scale]));
		w10.Position = 2;
		w10.Expand = false;
		w10.Fill = false;
		w10.Padding = ((uint)(5));
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.txt = new global::Gtk.Label();
		this.txt.Name = "txt";
		this.txt.LabelProp = global::Mono.Unix.Catalog.GetString("Welcome");
		this.txt.Selectable = true;
		this.vbox2.Add(this.txt);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.txt]));
		w11.Position = 0;
		w11.Expand = false;
		w11.Fill = false;
		this.vbox1.Add(this.vbox2);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vbox2]));
		w12.Position = 3;
		w12.Expand = false;
		w12.Fill = false;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 172;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.cbox.Changed += new global::System.EventHandler(this.Combochanged);
		this.refresh.Clicked += new global::System.EventHandler(this.Refresh);
		this.url.Clicked += new global::System.EventHandler(this.Url);
		this.play.Clicked += new global::System.EventHandler(this.Play);
		this.pause.Clicked += new global::System.EventHandler(this.Pause);
		this.stop.Clicked += new global::System.EventHandler(this.Stop);
		this.scale.ValueChanged += new global::System.EventHandler(this.OnScaleValueChanged);
		this.scale.FocusGrabbed += new global::System.EventHandler(this.OnScaleFocusGrabbed);
	}
}
